/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from 'nestjs-i18n'
/* prettier-ignore */
export type I18nTranslations = {
  auth: {
    invalidRegisterType: string
    emailOrPhoneRequired: string
    emailExists: string
    phoneExists: string
    phoneRegistrationNotImplemented: string
    oauthRegistrationNotImplemented: string
    invalidLoginType: string
    invalidCredentials: string
    phoneLoginNotImplemented: string
    oauthLoginNotImplemented: string
    userNotFound: string
    wrongPassword: string
    wrongOldPassword: string
    userHasNoLocalAuth: string
    passwordCannotBeSameAsOriginalPassword: string
    passwordTooShort: string
  }
  blog: {
    blogNotFound: string
    commentTooLong: string
    commentNotAuthor: string
    commentNotFound: string
  }
}
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>
