name: Check Changes and Bump

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            packages/fe/**
            packages/server/**

      - name: Check FE changes
        if: contains(steps.changed-files.outputs.all_changed_files, 'packages/fe/')
        run: |
          echo "FE_CHANGED=true" >> $GITHUB_ENV

      - name: Check Server changes
        if: contains(steps.changed-files.outputs.all_changed_files, 'packages/server/')
        run: |
          echo "SERVER_CHANGED=true" >> $GITHUB_ENV

      - name: Trigger Deploy
        if: env.FE_CHANGED == 'true' || env.SERVER_CHANGED == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'depoly.yml',
              ref: 'main',
              inputs: {
                fe_changed: process.env.FE_CHANGED === 'true',
                server_changed: process.env.SERVER_CHANGED === 'true'
              }
            }) 