name: Depoly

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: depoly
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.PATH }}
          touch a.txt

